version: '3.8'

services:
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python/app:/app
      - python_cache:/root/.cache
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    command: tail -f /dev/null  # Keep container running for development

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php:/app
    working_dir: /app
    command: tail -f /dev/null  # Keep container running for development

  typescript:
    build:
      context: ./typescript
      dockerfile: Dockerfile
    volumes:
      - ./typescript:/app
      - typescript_node_modules:/app/node_modules
    working_dir: /app
    command: tail -f /dev/null  # Keep container running for development

volumes:
  python_cache:
  typescript_node_modules: 
